import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { format } from 'date-fns';

// We don't need to register Helvetica as it's a standard PDF font
// but we will use the standard React PDF styles

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#000000',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  // Cover Styles
  coverContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  coverName: {
    fontSize: 48,
    color: '#FFFFFF',
    fontWeight: 'bold',
    marginBottom: 16,
    textAlign: 'center',
  },
  coverTagline: {
    fontSize: 16,
    color: '#888888',
    textAlign: 'center',
    maxWidth: '80%',
    lineHeight: 1.5,
  },
  coverBottomBar: {
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  coverValidation: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: 'bold',
    marginBottom: 8,
  },
  coverConfidential: {
    fontSize: 10,
    color: '#666666',
  },
  coverDate: {
    fontSize: 12,
    color: '#888888',
  },
  
  // Slide Styles
  headerContainer: {
    marginBottom: 30,
  },
  slideNumber: {
    fontSize: 12,
    color: '#666666',
    marginBottom: 4,
  },
  slideTitle: {
    fontSize: 10,
    color: '#888888',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  slideHeadline: {
    fontSize: 28,
    color: '#FFFFFF',
    fontWeight: 'bold',
    marginBottom: 24,
    lineHeight: 1.3,
  },
  slideContent: {
    fontSize: 14,
    color: '#AAAAAA',
    marginBottom: 20,
    lineHeight: 1.6,
  },
  bulletContainer: {
    flexDirection: 'row',
    marginBottom: 12,
    paddingRight: 40,
  },
  bulletIcon: {
    fontSize: 14,
    color: '#FFFFFF',
    marginRight: 10,
    marginTop: 2,
  },
  bulletText: {
    fontSize: 14,
    color: '#FFFFFF',
    lineHeight: 1.5,
    flex: 1,
  },
  
  // Slide Footer
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#222222',
    paddingTop: 10,
  },
  footerTextLeft: {
    fontSize: 10,
    color: '#666666',
  },
  footerTextRight: {
    fontSize: 10,
    color: '#666666',
  }
});

interface PitchDeckPDFProps {
  startupName: string;
  tagline: string;
  validationScore: number;
  slides: any[];
}

export default function PitchDeckPDF({ startupName, tagline, validationScore, slides }: PitchDeckPDFProps) {
  const currentDate = format(new Date(), 'MMMM yyyy');

  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.coverContainer}>
          <Text style={styles.coverName}>{startupName || "Startup"}</Text>
          <Text style={styles.coverTagline}>{tagline || "We are building the future."}</Text>
        </View>
        <View style={styles.coverBottomBar}>
          <View>
            {validationScore > 0 && (
              <Text style={styles.coverValidation}>Validation Score: {validationScore}/100</Text>
            )}
            <Text style={styles.coverConfidential}>CONFIDENTIAL</Text>
          </View>
          <Text style={styles.coverDate}>{currentDate}</Text>
        </View>
      </Page>

      {/* Content Pages */}
      {slides.map((slide, index) => (
        <Page key={index} size="A4" orientation="landscape" style={styles.page}>
          <View style={styles.headerContainer}>
            <Text style={styles.slideNumber}>{slide.number < 10 ? `0${slide.number}` : slide.number}</Text>
            <Text style={styles.slideTitle}>{slide.title}</Text>
          </View>
          
          <Text style={styles.slideHeadline}>{slide.headline}</Text>
          
          {slide.content && (
            <Text style={styles.slideContent}>{slide.content}</Text>
          )}
          
          {slide.bullets && slide.bullets.length > 0 && (
            <View>
              {slide.bullets.map((bullet: string, bIdx: number) => (
                <View key={bIdx} style={styles.bulletContainer}>
                  <Text style={styles.bulletIcon}>→</Text>
                  <Text style={styles.bulletText}>{bullet}</Text>
                </View>
              ))}
            </View>
          )}
          
          <View style={styles.footer}>
            <Text style={styles.footerTextLeft}>{startupName || "Startup"}</Text>
            <Text style={styles.footerTextRight}>Generated by StartupOS</Text>
          </View>
        </Page>
      ))}
    </Document>
  );
}
